default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  database: base_api_development
  username: root
  password: 1234

development:
  <<: *default

test:
  <<: *default
  database: base_api_test

staging:
  <<: *default

production:
  <<: *default
  